package com.einsteinford.kkweather.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.einsteinford.kkweather.bean.Basic;

import com.einsteinford.kkweather.db.BasicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig basicDaoConfig;

    private final BasicDao basicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        basicDaoConfig = daoConfigMap.get(BasicDao.class).clone();
        basicDaoConfig.initIdentityScope(type);

        basicDao = new BasicDao(basicDaoConfig, this);

        registerDao(Basic.class, basicDao);
    }
    
    public void clear() {
        basicDaoConfig.clearIdentityScope();
    }

    public BasicDao getBasicDao() {
        return basicDao;
    }

}
