package com.einsteinford.kkweather.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.einsteinford.kkweather.bean.Update;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UPDATE".
*/
public class UpdateDao extends AbstractDao<Update, Long> {

    public static final String TABLENAME = "UPDATE";

    /**
     * Properties of entity Update.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Loc = new Property(1, String.class, "loc", false, "LOC");
        public final static Property Utc = new Property(2, String.class, "utc", false, "UTC");
    }


    public UpdateDao(DaoConfig config) {
        super(config);
    }
    
    public UpdateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UPDATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LOC\" TEXT," + // 1: loc
                "\"UTC\" TEXT);"); // 2: utc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UPDATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Update entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String loc = entity.getLoc();
        if (loc != null) {
            stmt.bindString(2, loc);
        }
 
        String utc = entity.getUtc();
        if (utc != null) {
            stmt.bindString(3, utc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Update entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String loc = entity.getLoc();
        if (loc != null) {
            stmt.bindString(2, loc);
        }
 
        String utc = entity.getUtc();
        if (utc != null) {
            stmt.bindString(3, utc);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Update readEntity(Cursor cursor, int offset) {
        Update entity = new Update( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // loc
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // utc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Update entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLoc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUtc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Update entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Update entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Update entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
